const {chromium}=require('playwright');
const assert=require('assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const ctx=await b.newContext({viewport:{width:1440,height:1000}});const p=await ctx.newPage();const errors=[],bad=[],results=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('response',r=>{if(r.status()>=400)bad.push(r.url())});const base='http://127.0.0.1:8876/teacher-tools/';const pass=s=>{results.push(s);console.log('PASS',s)};
try{
await p.goto(base+'seating/');await p.locator('#generateAssignment').click();await p.locator('#confirmAssignment').click();const raw=await p.evaluate(()=>localStorage.getItem('teacher-tools.seating.state.v1'));
await p.goto(base+'hanja/');assert.equal(await p.locator('.hanja-student').count(),10);await p.locator('#start').click();assert(await p.locator('#manager').isVisible());pass('empty DB blocks start; canonical registry loaded');
const rows=[['山','메','산'],['水','물','수'],['火','불','화'],['木','나무','목']];
for(const [text,meaning,reading]of rows){await p.locator('#hanzi').fill(text);await p.locator('#meaning').fill(meaning);await p.locator('#reading').fill(reading);await p.locator('#entryForm button[type=submit]').click()}
assert.equal(await p.locator('.entry-card').count(),4);await p.locator('#hanzi').fill('山水');assert.equal(await p.locator('#hanzi').inputValue(),'山水');await p.locator('#meaning').fill('산수');await p.locator('#reading').fill('산수');await p.locator('#entryForm button[type=submit]').click();assert.equal(await p.locator('.entry-card').count(),4);pass('single Han input unrestricted; save rejects multiple characters');
await p.locator('[data-type=word]').click();for(const [text,meaning,reading]of [['山水','산과 물','산수'],['火山','불을 뿜는 산','화산']]){await p.locator('#hanzi').fill(text);await p.locator('#meaning').fill(meaning);await p.locator('#reading').fill(reading);await p.locator('#entryForm button[type=submit]').click()}
await p.reload();assert.equal(await p.locator('.entry-card').count(),4);pass('single and word DB save/reload');
await p.locator('[data-panel=questions]').click();await p.locator('#target').selectOption('single');await p.locator('#perStudent').fill('3');await p.locator('#perStudent').press('Tab');await p.locator('.hanja-student').last().click();await p.screenshot({path:'work/hanja-manager.png',fullPage:true});await p.locator('#start').click();await p.locator('#game').waitFor({state:'visible'});const name=await p.locator('#studentName').textContent();let previous='';
for(let i=1;i<=3;i++){assert.equal(await p.locator('#studentName').textContent(),name);assert((await p.locator('#progress').textContent()).includes(`문제 ${i} / 3`));const prompt=await p.locator('#prompt').textContent();assert.notEqual(prompt,previous);previous=prompt;const row=rows.find(r=>r[0]===prompt),answer=row[1]+' '+row[2];const before=await p.locator('#progress').textContent();const buttons=p.locator('#options button');for(let j=0;j<await buttons.count();j++){if(await buttons.nth(j).textContent()!==answer){await buttons.nth(j).click();break}}assert.equal(await p.locator('#progress').textContent(),before);assert.equal(await p.locator('#prompt').textContent(),prompt);await p.getByRole('button',{name:answer,exact:true}).click();if(i===1){assert(await p.locator('#gameSprite').evaluate(e=>e.classList.contains('jump')));await p.screenshot({path:'work/hanja-game.png',fullPage:true})}await p.waitForTimeout(800)}assert.notEqual(await p.locator('#studentName').textContent(),name);pass('3 consecutive questions per student; no immediate repeats; wrong answers stay; jump and next student');
await p.locator('#endGame').click();await p.locator('#mode').selectOption('manual');await p.locator('#target').selectOption('word');await p.locator('#direction').selectOption('reverse');await p.locator('#perStudent').fill('1');await p.locator('#perStudent').press('Tab');for(let i=1;i<9;i++)await p.locator('.hanja-student').nth(i).click();await p.locator('#start').click();assert(await p.locator('#judgement').isHidden());await p.locator('#reveal').click();assert(await p.locator('#answer').isVisible());const before=await p.locator('#progress').textContent();await p.locator('#wrong').click();assert.equal(await p.locator('#progress').textContent(),before);await p.locator('#correct').click();await p.waitForTimeout(800);assert((await p.locator('#progress').textContent()).includes('수업 완료'));pass('manual reveal gate, wrong stays, correct completion');
assert.equal(await p.evaluate(()=>localStorage.getItem('teacher-tools.seating.state.v1')),raw);pass('Seating state byte-for-byte unchanged by Hanja');await p.locator('#endGame').click();await p.reload();assert.equal(await p.locator('.hanja-student[aria-pressed=true]').count(),10);await p.locator('[data-panel=questions]').click();assert.equal(await p.locator('#mode').inputValue(),'manual');pass('settings persist; participation is session-only');
for(const width of [1440,768,390]){await p.setViewportSize({width,height:1000});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`work/hanja-${width}.png`,fullPage:true})}pass('desktop tablet mobile overflow');assert.deepEqual(errors,[]);assert.deepEqual(bad,[]);pass('no console errors or asset 404');
}catch(e){console.error(e);results.push('FAIL '+e.stack);process.exitCode=1}fs.writeFileSync('work/hanja-results.json',JSON.stringify({results,errors,bad},null,2));await b.close()})();
