const {chromium}=require('playwright');
const fs=require('fs');const assert=require('assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const ctx=await browser.newContext({viewport:{width:1280,height:1000},acceptDownloads:true});
 const p=await ctx.newPage();const results=[],errors=[],bad=[],requests=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('request',r=>requests.push(r.url()));p.on('response',r=>{if(r.status()>=400)bad.push(r.url())});
 const pass=(name)=>{results.push({name,result:'PASS'});console.log('PASS',name)};
 const base='http://127.0.0.1:8876/teacher-tools/';
 try {
 await p.goto(base);assert.equal(await p.locator('.app-card').count(),7);pass('Hub loads with seven registry cards');
 assert.equal(await p.locator('.app-card[href]').count(),2);
 for(const id of ['mario-game','mario-manager','feedback','project-c','role-manager']){
  const card=p.locator(`[data-app-id="${id}"]`);assert.equal(await card.evaluate(e=>e.tagName),'ARTICLE');assert.equal(await card.getAttribute('tabindex'),null);await card.click();await p.keyboard.press('Enter');assert.equal(p.url(),base);
 }
 pass('Missing URLs and development cards do not navigate by mouse/Enter');
 for(const width of [1280,768,390,320]){await p.setViewportSize({width,height:1000});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const cols=await p.locator('.app-grid').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length);assert.equal(cols,width>850?3:width>520?2:1);await p.screenshot({path:`work/hub-${width}.png`,fullPage:true})}pass('Desktop/tablet/mobile grid and overflow');
 await p.setViewportSize({width:1280,height:1000});await p.goto(base);await p.keyboard.press('Tab');assert.equal(await p.locator(':focus').getAttribute('class'),'skip-link');await p.keyboard.press('Tab');await p.keyboard.press('Tab');assert.equal(await p.locator(':focus').getAttribute('data-app-id'),'seating');await p.keyboard.press('Enter');await p.waitForURL(base+'seating/');pass('Keyboard skips non-interactive cards and opens Seating');
 await p.goto(base+'seating/');await p.reload();await p.locator('#generateAssignment').waitFor();pass('Seating direct load and refresh under repository prefix');
 await p.locator('[data-tab="settings"]').click();await p.locator('#className').fill('STEP2 테스트반');await p.locator('#className').press('Tab');await p.reload();await p.locator('[data-tab="settings"]').click();assert.equal(await p.locator('#className').inputValue(),'STEP2 테스트반');pass('Save and reload restore');
 await p.locator('#rowPlus').click();const rows=await p.evaluate(()=>classState.layout.rows);await p.locator('#undoButton').click();assert.equal(await p.evaluate(()=>classState.layout.rows),rows-1);await p.locator('#redoButton').click();assert.equal(await p.evaluate(()=>classState.layout.rows),rows);pass('Undo and redo via UI');
 await p.locator('#generateAssignment').click();assert.equal(await p.evaluate(()=>previewAssignments.length),10);await p.locator('#confirmAssignment').click();assert.equal(await p.evaluate(()=>classState.assignments.length),10);assert.equal(await p.evaluate(()=>new Set(classState.assignments.map(a=>a.seatId)).size),10);pass('Generate and confirm complete unique seating');
 await p.locator('[data-tab="history"]').click();await p.locator('[data-view-history]').first().click();assert(await p.locator('#historyBanner').isVisible());await p.locator('#exitHistoryView').click();pass('History snapshot viewing and return');
 await p.locator('[data-tab="teacher"]').click();await p.locator('#avatarMale').click();await p.locator('#avatarSkin').selectOption('1');assert.equal(await p.evaluate(()=>classState.teacherAvatar.gender),'male');pass('Teacher avatar UI');
 await p.locator('[data-tab="settings"]').click();const downloadPromise=p.waitForEvent('download');await p.locator('#exportJson').click();const download=await downloadPromise;await download.saveAs('work/backup.json');const saved=JSON.parse(fs.readFileSync('work/backup.json','utf8'));assert.equal(saved.classState.className,'STEP2 테스트반');pass('JSON Export download');
 await p.locator('#className').fill('변경반');await p.locator('#className').press('Tab');p.once('dialog',d=>d.accept());await p.locator('#importJsonFile').setInputFiles('work/backup.json');await p.waitForFunction(()=>document.getElementById('className').value==='STEP2 테스트반');assert.deepEqual(await p.evaluate(()=>JSON.parse(JSON.stringify(classState))),await p.evaluate(data=>JSON.parse(JSON.stringify(parseBackupText(JSON.stringify(data)))),saved));pass('JSON Import restores exported state');
 const raw=await p.evaluate(()=>localStorage.getItem(STORAGE_KEY));await p.locator('#importJsonFile').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{broken')});await p.waitForFunction(()=>document.getElementById('dataTransferStatus').textContent.includes('실패'));assert.equal(await p.evaluate(()=>localStorage.getItem(STORAGE_KEY)),raw);pass('Corrupted import rejected without storage mutation');
 await p.locator('#openPlayback').click();await p.locator('#instant').click();await p.locator('#simpleViewButton').waitFor({state:'visible'});await p.screenshot({path:'work/playback.png',fullPage:true});await p.locator('#simpleViewButton').click();const jpgPromise=p.waitForEvent('download');await p.locator('#downloadJpg').click();const jpg=await jpgPromise;await jpg.saveAs('work/seating.jpg');const bytes=fs.readFileSync('work/seating.jpg');assert.equal(bytes[0],255);assert.equal(bytes[1],216);assert(bytes.length>1000);pass('Public playback, simple view, JPG export');
 await p.locator('#simpleBackToTeacher').click();await p.screenshot({path:'work/seating.png',fullPage:true});
 const assetFiles=fs.readdirSync('shared/assets',{recursive:true}).filter(f=>fs.statSync('shared/assets/'+f).isFile());
 for(const f of assetFiles){const r=await ctx.request.get(base+'shared/assets/'+f);assert.equal(r.status(),200,f)}pass(`All ${assetFiles.length} shared assets served under /teacher-tools/shared/assets/`);
 assert(requests.some(u=>u.includes('/assets/students/')));assert(requests.some(u=>u.includes('/assets/teacher/')));assert(requests.some(u=>u.includes('/assets/playback/')));assert.equal(bad.length,0);assert.equal(errors.length,0);assert(requests.every(u=>u.startsWith(base)||u.startsWith('blob:')));pass('Dynamic student/teacher/playback assets, no failed or external requests, no console errors');
 const touch=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const mobile=await touch.newPage();await mobile.goto(base);for(const id of ['project-c','role-manager','feedback','mario-game','mario-manager']){await mobile.locator(`[data-app-id="${id}"]`).tap();assert.equal(mobile.url(),base)}await touch.close();pass('Disabled and unconfigured cards do not navigate on touch');
 // Instrument only a new isolated test page to observe Hub storage access.
 const guard=await ctx.newPage();await guard.addInitScript(()=>{for(const key of ['localStorage','sessionStorage'])Object.defineProperty(window,key,{get(){throw Error('Unexpected Hub storage access')}})});const ge=[];guard.on('pageerror',e=>ge.push(e.message));await guard.goto(base);assert.equal(await guard.locator('.app-card').count(),7);assert.equal(ge.length,0);await guard.close();pass('Hub works with browser storage access blocked');
 }catch(e){results.push({name:'Suite failure',result:'FAIL',detail:e.stack});console.error(e);process.exitCode=1}
 fs.writeFileSync('work/browser-results.json',JSON.stringify({date:'2026-10-06',browser:await browser.version(),environment:'macOS Chrome headless / HTTP loopback / repository subpath',results,errors,bad,requests:[...new Set(requests)]},null,2));await browser.close();
})();
