import {readStudents,STUDENT_STORAGE_KEY} from '../shared/student-registry.js';
import {defaults,shuffle,validateEntry,validateSettings,question,checkReady} from './engine.js';
const KEY='teacher-tools.hanja.data.v1', $=id=>document.getElementById(id);
let db=[],settings={...defaults},type='single',editId=null,students=[],excluded=new Set(),session=null,advanceTimer,noticeTimer,audio,lastRaw=null,storageBlocked=false;
function notify(message){$('notice').textContent=message;$('notice').classList.remove('hidden');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').classList.add('hidden'),7000)}
function load(){try{lastRaw=localStorage.getItem(KEY);if(lastRaw){const data=JSON.parse(lastRaw);if(data.version!==1||!Array.isArray(data.entries))throw Error('저장 형식 오류');const ids=new Set();data.entries.forEach(e=>{validateEntry(e);if(typeof e.id!=='string'||ids.has(e.id)||typeof e.enabled!=='boolean')throw Error('항목 형식 오류');ids.add(e.id)});db=data.entries;settings=validateSettings(data.settings)}}catch{storageBlocked=true;$('saveStatus').textContent='저장 데이터 확인 필요 · 덮어쓰기 중지';notify('한자 데이터를 읽지 못했습니다. 기존 저장 데이터는 덮어쓰지 않습니다.')}for(const key of Object.keys(defaults))$(key).value=settings[key]}
function save(){if(storageBlocked){notify('저장 데이터 오류 또는 다른 탭 변경으로 저장이 중지되었습니다. 새로고침 후 확인해 주세요.');return false}try{if(localStorage.getItem(KEY)!==lastRaw){storageBlocked=true;throw Error('다른 탭에서 데이터가 변경되었습니다. 새로고침해 주세요.')}const raw=JSON.stringify({version:1,entries:db,settings});localStorage.setItem(KEY,raw);if(localStorage.getItem(KEY)!==raw)throw Error('저장 확인 실패');lastRaw=raw;$('saveStatus').textContent='이 브라우저에 저장됨';return true}catch(e){$('saveStatus').textContent='저장 실패 · 변경 내용 확인 필요';notify(e.message);return false}}
function panel(name){$('dataPanel').classList.toggle('hidden',name!=='data');$('questionsPanel').classList.toggle('hidden',name!=='questions');document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('on',b.dataset.panel===name))}
function resetForm(){editId=null;$('entryForm').reset();$('editTitle').textContent=type==='single'?'한자 등록':'한자어 등록';$('textLabel').textContent=type==='single'?'한자':'조합 한자';$('meaningLabel').textContent=type==='single'?'훈':'뜻';$('readingLabel').textContent=type==='single'?'음':'읽기'}
function renderDb(){const entries=db.filter(e=>e.type===type);$('dbTitle').textContent=type==='single'?'단일 한자':'한자어';$('dbSummary').textContent=`${entries.length}개 등록 · ${entries.filter(e=>e.enabled).length}개 사용`;$('emptyDb').classList.toggle('hidden',entries.length>0);$('entries').replaceChildren();for(const e of entries){const card=document.createElement('article');card.className='entry-card'+(e.enabled?'':' off');const h=document.createElement('h2');h.textContent=e.text;const info=document.createElement('p');info.textContent=`${e.meaning} · ${e.reading}`;const meta=document.createElement('small');meta.textContent=`${e.enabled?'사용':'제외'} · 비중 ${e.weight}`;const actions=document.createElement('div');actions.className='actions';for(const [label,fn] of [['수정',()=>{editId=e.id;panel('data');$('editTitle').textContent='항목 수정';$('hanzi').value=e.text;$('meaning').value=e.meaning;$('reading').value=e.reading;$('weight').value=e.weight;$('enabled').checked=e.enabled;$('hanzi').focus()}],['삭제',()=>{if(!confirm(`${e.text} 항목을 삭제할까요?`))return;const before=db;db=db.filter(x=>x.id!==e.id);if(!save())db=before;else if(editId===e.id)resetForm();renderDb()}]]){const b=document.createElement('button');b.textContent=label;b.onclick=fn;actions.append(b)}card.append(h,info,meta,actions);$('entries').append(card)}}
function refreshRoster(){try{students=readStudents();$('start').disabled=false;renderStudents()}catch(e){students=[];$('start').disabled=true;renderStudents();notify(`학생명단을 읽을 수 없습니다. ${e.message}`)}}
function renderStudents(){$('studentCards').replaceChildren();$('rosterSummary').textContent=`참가 ${students.filter(s=>!excluded.has(s.id)).length} / ${students.length}명 · 클릭하여 이번 수업 참가/제외`;if(!students.length){const p=document.createElement('p');p.textContent='자리배치 매니저에서 학생명단을 먼저 저장해 주세요.';$('studentCards').append(p)}for(const s of students){const b=document.createElement('button');b.className='hanja-student';b.setAttribute('aria-pressed',String(!excluded.has(s.id)));b.setAttribute('aria-label',`${s.name} 이번 수업 ${excluded.has(s.id)?'제외':'참가'}`);const sprite=document.createElement('div');sprite.className='hanja-sprite';sprite.style.backgroundImage=`url("${s.sprite}")`;const name=document.createElement('span');name.textContent=s.name;const status=document.createElement('small');status.textContent=excluded.has(s.id)?'제외':'참가';b.append(sprite,name,status);b.onclick=()=>{excluded.has(s.id)?excluded.delete(s.id):excluded.add(s.id);renderStudents()};$('studentCards').append(b)}}
function readSettings(){return validateSettings({target:$('target').value,direction:$('direction').value,mode:$('mode').value,perStudent:Number($('perStudent').value),choices:Number($('choices').value)})}
function sheetLib(){if(!window.XLSX)throw Error('스프레드시트 기능을 불러오지 못했습니다. 인터넷 연결 후 다시 시도해 주세요.');return window.XLSX}
function sheetRows(entries,kind){return entries.filter(e=>e.type===kind).map(e=>kind==='single'?{'한자':e.text,'훈':e.meaning,'음':e.reading,'사용':e.enabled?'사용':'제외','출제비중':e.weight}:{'한자어':e.text,'읽기':e.reading,'뜻':e.meaning,'사용':e.enabled?'사용':'제외','출제비중':e.weight})}
function exportSheet(){try{const XLSX=sheetLib(),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(sheetRows(db,'single'),{header:['한자','훈','음','사용','출제비중']}),'단일 한자');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(sheetRows(db,'word'),{header:['한자어','읽기','뜻','사용','출제비중']}),'한자어');XLSX.writeFile(wb,'한자학습매니저_현재데이터.xlsx')}catch(e){notify(e.message)}}
function boolCell(v){const s=String(v??'사용').trim().toLowerCase();if(['사용','o','yes','true','1','y'].includes(s))return true;if(['제외','x','no','false','0','n'].includes(s))return false;throw Error(`사용 열은 '사용' 또는 '제외'로 입력해 주세요: ${v}`)}
function rowsToEntries(rows,kind){const out=[];for(let i=0;i<rows.length;i++){const r=rows[i],text=String(r[kind==='single'?'한자':'한자어']??'').trim();if(!text)continue;const entry={id:crypto.randomUUID(),type:kind,text,meaning:String(r[kind==='single'?'훈':'뜻']??'').trim(),reading:String(r[kind==='single'?'음':'읽기']??'').trim(),enabled:boolCell(r['사용']),weight:Number(r['출제비중']??1)};try{validateEntry(entry)}catch(e){throw Error(`${kind==='single'?'단일 한자':'한자어'} 시트 ${i+2}행: ${e.message}`)}out.push(entry)}return out}
async function importSheet(file){try{const XLSX=sheetLib(),data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array'});const read=name=>wb.Sheets[name]?XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:''}):[];const incoming=[...rowsToEntries(read('단일 한자'),'single'),...rowsToEntries(read('한자어'),'word')];if(!incoming.length)throw Error('가져올 한자/한자어가 없습니다. 시트 이름과 내용을 확인해 주세요.');const seen=new Set();for(const e of incoming){const k=e.type+'|'+e.text;if(seen.has(k))throw Error(`업로드 파일에 중복 항목이 있습니다: ${e.text}`);seen.add(k)}const mode=$('importMode').value;if(mode==='replace'&&!confirm(`현재 등록 데이터를 모두 지우고 ${incoming.length}개 항목으로 교체할까요?`))return;const before=db;if(mode==='replace')db=incoming;else{const map=new Map(db.map(e=>[e.type+'|'+e.text,e]));for(const e of incoming){const k=e.type+'|'+e.text,old=map.get(k);map.set(k,old?{...e,id:old.id}:e)}db=[...map.values()]}if(!save()){db=before;return}resetForm();renderDb();notify(`${incoming.length}개 항목을 스프레드시트에서 가져왔습니다.`)}catch(e){notify(e.message)}finally{$('sheetFile').value=''}}
function sound(success){try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const t=audio.currentTime;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(success?660:180,t);osc.frequency.exponentialRampToValueAtTime(success?990:110,t+.16);gain.gain.setValueAtTime(.12,t);gain.gain.exponentialRampToValueAtTime(.001,t+.25);osc.connect(gain);gain.connect(audio.destination);osc.start(t);osc.stop(t+.26)}catch{/* Audio availability never blocks classroom progression. */}}
function start(){try{settings=readSettings();checkReady(db,settings);refreshRoster();const participants=students.filter(s=>!excluded.has(s.id));if(!participants.length)throw Error('이번 수업에 참가할 학생을 선택해 주세요.');session={students:shuffle(participants),settings:{...settings},db:db.map(e=>({...e})),studentIndex:0,solved:0,lastId:null,locked:false,revealed:false};$('manager').classList.add('hidden');$('game').classList.remove('hidden');nextQuestion()}catch(e){session=null;notify(e.message)}}
function nextQuestion(){if(!session)return;if(session.studentIndex>=session.students.length){$('progress').textContent=`수업 완료 · ${session.students.length}명 × ${session.settings.perStudent}문제`;$('questionType').textContent='모두 마쳤어요';$('prompt').textContent='수고했어요!';$('options').replaceChildren();$('manual').classList.add('hidden');$('feedback').textContent='모든 학생이 문제를 풀었습니다.';$('currentStudent').classList.add('hidden');session.locked=true;return}session.q=question(session.db,session.settings,session.lastId);session.lastId=session.q.id;session.locked=false;session.revealed=false;renderQuestion()}
function renderQuestion(){const s=session.students[session.studentIndex],q=session.q;$('progress').textContent=`학생 ${session.studentIndex+1} / ${session.students.length} · ${s.name} 문제 ${session.solved+1} / ${session.settings.perStudent}`;$('questionType').textContent=`${q.type==='single'?'단일 한자':'한자어'} · ${q.direction==='forward'?'훈음·읽기를 답하세요':'한자를 답하세요'}`;$('prompt').textContent=q.prompt;$('feedback').textContent='';$('currentStudent').classList.remove('hidden');$('studentName').textContent=s.name;$('gameSprite').style.backgroundImage=`url("${s.sprite}")`;$('gameSprite').classList.remove('jump');$('options').replaceChildren();$('manual').classList.toggle('hidden',session.settings.mode!=='manual');$('answer').classList.add('hidden');$('judgement').classList.add('hidden');$('reveal').classList.remove('hidden');$('reveal').disabled=false;$('correct').disabled=false;$('wrong').disabled=false;if(session.settings.mode==='choice')for(const option of q.options){const b=document.createElement('button');b.textContent=option;b.onclick=()=>judge(option===q.answer);$('options').append(b)}$('options').classList.toggle('hidden',session.settings.mode!=='choice')}
function judge(correct){if(!session||session.locked||(session.settings.mode==='manual'&&!session.revealed))return;sound(correct);if(!correct){$('feedback').textContent='✕ 다시 도전해 보세요.';return}session.locked=true;$('feedback').textContent='O 정답!';$('gameSprite').classList.add('jump');document.querySelectorAll('#options button,#judgement button').forEach(b=>b.disabled=true);advanceTimer=setTimeout(()=>{if(!session)return;session.solved++;if(session.solved>=session.settings.perStudent){session.studentIndex++;session.solved=0}nextQuestion()},700)}
$('entryForm').onsubmit=e=>{e.preventDefault();if(e.isComposing)return;try{const entry=validateEntry({id:editId||crypto.randomUUID(),type,text:$('hanzi').value.trim(),meaning:$('meaning').value.trim(),reading:$('reading').value.trim(),weight:Number($('weight').value),enabled:$('enabled').checked});if(db.some(x=>x.text===entry.text&&x.type===entry.type&&x.id!==entry.id))throw Error('이미 등록된 항목입니다. 기존 항목을 수정해 주세요.');const before=db;db=editId?db.map(x=>x.id===editId?entry:x):[...db,entry];if(!save()){db=before;return}resetForm();renderDb()}catch(error){notify(error.message)}};
$('entryForm').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.isComposing||e.keyCode===229))e.preventDefault()});
$('settingsForm').onchange=()=>{try{const before=settings;settings=readSettings();if(!save())settings=before}catch(e){notify(e.message)}};
$('settingsForm').onsubmit=e=>e.preventDefault();
for(const b of document.querySelectorAll('[data-type]'))b.onclick=()=>{type=b.dataset.type;document.querySelectorAll('[data-type]').forEach(x=>x.classList.toggle('on',x===b));resetForm();renderDb();panel('data')};
for(const b of document.querySelectorAll('[data-panel]'))b.onclick=()=>panel(b.dataset.panel);
$('newEntry').onclick=()=>{resetForm();panel('data');$('hanzi').focus()};$('cancelEdit').onclick=resetForm;$('refreshRoster').onclick=refreshRoster;$('exportSheet').onclick=exportSheet;$('importSheet').onclick=()=>$('sheetFile').click();$('sheetFile').onchange=e=>{const file=e.target.files?.[0];if(file)importSheet(file)};$('start').onclick=start;
$('reveal').onclick=()=>{if(!session||session.locked)return;session.revealed=true;$('answer').textContent=session.q.answer+(session.q.type==='word'?` · ${session.q.meaning}`:'');$('answer').classList.remove('hidden');$('judgement').classList.remove('hidden');$('reveal').classList.add('hidden')};$('correct').onclick=()=>judge(true);$('wrong').onclick=()=>judge(false);
$('endGame').onclick=()=>{clearTimeout(advanceTimer);session=null;$('game').classList.add('hidden');$('manager').classList.remove('hidden');refreshRoster()};
window.addEventListener('storage',e=>{if(e.key===STUDENT_STORAGE_KEY||e.key===null){if(!session)refreshRoster();else notify('학생명단이 변경되었습니다. 현재 수업은 시작할 때의 명단으로 계속합니다.')}if(e.key===KEY||e.key===null){storageBlocked=true;$('saveStatus').textContent='다른 탭에서 변경됨 · 새로고침 필요';notify('다른 탭의 한자 데이터가 변경되었습니다. 새로고침해 주세요.')}});
load();resetForm();renderDb();refreshRoster();